language: android
jdk:
 - oraclejdk8
android:
  components:
    - build-tools-25.0.0
    - android-25
    - extra-android-m2repository
  licenses:
    - '.+'
notifications:
  email: false
script:
 - chmod +x gradlew && ./gradlew test